wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.20
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1656528122
    t:
      1:
      - 1
      - 2
      - 3
      - 30
      - 55
      2:
      - 1
      - 2
      - 3
      - 30
      - 55
      4: 3.8.13
      5: 0.12.20
      8:
      - 1
      - 5
