---
# The set of runnable cBench benchmarks. Enumerated using:
#
#     >>> import compiler_gym
#     >>> env = compiler_gym.make("llvm-v0")
#     >>> for benchmark in env.datasets["benchmark://cbench-v1"]:
#     ...     env.reset(benchmark)
#     ...     if env.observation.IsRunnable():
#     ...         print(benchmark)
#
benchmarks:
    - uris:
          - benchmark://cbench-v1/bitcount
          - benchmark://cbench-v1/blowfish
          - benchmark://cbench-v1/bzip2
          - benchmark://cbench-v1/crc32
          - benchmark://cbench-v1/dijkstra
          - benchmark://cbench-v1/gsm
          - benchmark://cbench-v1/jpeg-c
          - benchmark://cbench-v1/jpeg-d
          - benchmark://cbench-v1/patricia
          - benchmark://cbench-v1/qsort
          - benchmark://cbench-v1/sha
          - benchmark://cbench-v1/stringsearch
          - benchmark://cbench-v1/stringsearch2
          - benchmark://cbench-v1/susan
          - benchmark://cbench-v1/tiff2bw
          - benchmark://cbench-v1/tiff2rgba
          - benchmark://cbench-v1/tiffdither
          - benchmark://cbench-v1/tiffmedian
