---
# TODO: How to add user benchmark without specifying uris
# benchmarks:
#     - dataset: benchmark://poj104-v0
#       max_benchmarks: 5

benchmarks:
    - uris:
        #   - benchmark://loop_tool_simple-v0/simple
        #   - benchmark://loop_tool_simple-v0/mm
          - benchmark://loop_tool_simple-v0/conv
          - benchmark://loop_tool_simple-v0/mm128
          - benchmark://loop_tool_simple-v0/mm256